name: Build BeagleBone Black Image with Tester

on:
  push:
    branches: [ beagle-tester ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Buildroot
      uses: actions/checkout@v4
      with:
        
        repository: 'buildroot/buildroot'
        ref: '2024.05.2'
        path: 'buildroot'

    - name: Checkout beagle-tester
      uses: actions/checkout@v4
      with:
        repository: 'VidhuSarwal/beagle-tester'
        path: 'buildroot/package/beagle-tester'

    - name: Install Buildroot dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libncurses5-dev cpio

    - name: Configure and Build for BeagleBone Black
      working-directory: ./buildroot
      run: |
        # 1. Apply the default BeagleBone Black configuration
        make beaglebone_defconfig
        
        # 2. Enable the beagle-tester package by adding it to the .config file
        echo "BR2_PACKAGE_BEAGLE_TESTER=y" >> .config
        
        # 3. Update the configuration to include any dependencies for the new package
        make olddefconfig

        # 4. Run the build process
        echo "Starting Buildroot make..."
        make

    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: beaglebone-black-image
        path: buildroot/output/images/sdcard.img
